# Dockerfile.secrets_manager
FROM python:3.9-slim
WORKDIR /app

# Copy the secrets manager specific requirements and install them
COPY broker/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the secrets manager application
COPY broker/kv_server.py ./

CMD ["python", "kv_server.py"]