# Use nginx stable alpine image
FROM nginx:stable-alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the Nginx configuration file from the project into the container
COPY ./deployment/nginx/nginx.conf /etc/nginx/conf.d/nginx.conf

# Expose port 80 to the outside world
EXPOSE 80

# Start Nginx and keep it running in the foreground
CMD ["nginx", "-g", "daemon off;"]
